website/market/urls.py
from django.urls import path

from .views import home, market, add_market, delete_market, update_market
from .views import register_user, logout_user
from .views import ingredients_list, add_ingredient, delete_ingredient
from .views import recipes_list, recipe, update_recipe, add_recipe, delete_recipe
from .views import add_ingredient_to_recipe, delete_ingredient_from_recipe
from .views import add_recipe_to_market, delete_recipe_from_market
from .views import generate_list
# from .views import market

urlpatterns = [
    path('', home, name='home'),
    path('add_market/',add_market,name='add_market'),
    path('market/<int:pk>/',market,name='market'),
    path('delete_market/<int:pk>/',delete_market,name='delete_market'),
    path('update_market/<int:pk>/',update_market,name='update_market'),
    path('register/', register_user, name='register'),
    path('logout/', logout_user, name='logout'),
    path('ingredients_list/', ingredients_list, name='ingredients_list'),
    path('add_ingredient/', add_ingredient, name='add_ingredient'),
    path('delete_ingredient/<int:pk>/', delete_ingredient, name='delete_ingredient'),
    path('recipes_list/', recipes_list, name='recipes_list'),
    path('add_recipe/', add_recipe, name='add_recipe'),
    path('recipe/<int:pk>/', recipe, name='recipe'),
    path('update_recipe/<int:pk>/', update_recipe, name='update_recipe'),
    path('delete_recipe/<int:pk>/', delete_recipe, name='delete_recipe'),
    path('add_ingredient_to_recipe/<int:pk>/', add_ingredient_to_recipe, name='add_ingredient_to_recipe'),
    path('delete_ingredient_from_recipe/<int:pk_recipe>/<int:pk_ingredient>/', delete_ingredient_from_recipe, name='delete_ingredient_from_recipe'),
    path('add_recipe_to_market/<int:pk>/', add_recipe_to_market, name='add_recipe_to_market'),
    path('delete_recipe_from_market/<int:pk_market>/<int:pk_recipe>/', delete_recipe_from_market, name='delete_recipe_from_market'),
    path('generate_list/<int:pk>/', generate_list, name='generate_list'),
]

website/market/models.py
from django.db import models
from django.contrib.auth.models import User

from .choices import CATEGORIES, UNITIES


class Ingredient(models.Model):
    """ A class to represent a ingredient of differents kitchen recipe

    Attributes:
        name (string) : ingredient name
            constraints {
                max_length : 20
                unique : True
            }
        user (class User): User Foreing key
        categorie (string) : ingredient categorie (ex Fruits, vegetables)
            constraints {
                max_length : 1
                default : 'V'
            }
    """

    name = models.CharField(max_length=20, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    categorie = models.CharField(max_length=1, default='V', choices=CATEGORIES)

    def __str__(self):
        return f'{self.name}'

class Recipe(models.Model):
    """A class to represent a kitchen recipe

    Attributes:
        name (string): recipe name
            constraints {
                max_length : 20
                unique : True
            }
        user (class User): User Foreing key
        ingredients (class Ingredient): an ingredient
    """
    name = models.CharField(max_length=20, unique=True)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    ingredients = models.ManyToManyField(Ingredient, through='IngredientDetail')

    def __str__(self):
        return f'{self.name}'

class IngredientDetail(models.Model):
    """A class to represent the ingredient detail of a kitchen recipe

    Attributes:
        pk_ingredient (int) : ingredient foreign key
        pk_recipe (int) : recipe foreign key.
        unity (string) : ingredient quantity unit, two differents option gr and un.
            constraints {
                max_length : 2
                default : 'gr'
            }
        value (int) : quantity value.
            constraints {
                default : 0
            }
    """
    ingredient = models.ForeignKey(Ingredient, on_delete=models.CASCADE)
    recipe = models.ForeignKey(Recipe, on_delete=models.CASCADE)
    unity = models.CharField(max_length=2, default='gr', choices=UNITIES)
    value = models.IntegerField(default=0, null=False)

    def __str__(self):
        return "{}_{}".format(self.recipe.__str__(), self.ingredient.__str__())


class MarketList(models.Model):
    """A class to represent a market shopping list, with contains all the recipe

    Attribute:
        name (string): market list name
        user (class): user foreign key
        recipe (class Recipe): recipe foreign key
    """
    name = models.CharField(max_length=20)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    recipe = models.ManyToManyField(Recipe)

    def __str__(self):
        return f'{self.name}'

    def ingredients_list(self):
        list_detail = {}

        recipes = self.recipe.all()
        for each_recipe in recipes:
            ingredients = IngredientDetail.objects.filter(recipe=each_recipe)
            for ingredient in ingredients:
                ingredients_id = ingredient.ingredient.id
                gr_value, un_value = (ingredient.value,0) if ingredient.unity == UNITIES[0][0] else (0,ingredient.value)
                if ingredients_id in list_detail.keys():
                    list_detail[ingredients_id][UNITIES[0][0]] += gr_value
                    list_detail[ingredients_id][UNITIES[1][0]] += un_value

                else:
                    list_detail[ingredients_id] = {
                        'name': ingredient.ingredient.name,
                        UNITIES[0][0]: gr_value,
                        UNITIES[1][0]: un_value
                    }
        return list(list_detail.values())

website/market/templates/add_ingredient.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Add New Ingredients</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{form.name}}
        {{form.categorie}}
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{% url 'ingredients_list' %}" class="btn btn-secondary">Go Back</a>
        </div>
    </form>

</div>
{% endblock%}

website/market/templates/add_ingredient_to_recipe.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    {% if recipe%}
        <h1>Add an Ingredients to the recipe {{recipe.name}}</h1>

        <form action="" method="post">
            {% csrf_token %}
            {{form.ingredient}}
            {{form.value}}
            {{form.unity}}
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'recipe' recipe.id  %}" class="btn btn-secondary">Go Back</a>
        </form>
    {% endif %}
</div>
{% endblock %}

website/market/templates/add_market.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Add New Market List</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{form.name}}
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{% url 'home' %}" class="btn btn-secondary">Go Back</a>
        </div>
    </form>
</div>
{% endblock %}

website/market/templates/add_recipe.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Add New Recipe</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{form.name}}
        <div class="d-flex justify-content-between">
            <button type="submit" class="btn btn-primary">Create</button>
            <a href="{% url 'recipes_list' %}" class="btn btn-secondary">Go Back</a>
        </div>
    </form>

</div>
{% endblock%}

website/market/templates/add_recipe_to_market.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    {% if market_list %}
        <h1>Add an Recipe to Market List {{market_list.name}}</h1>

        <form action="" method="post">
            {% csrf_token %}
            {{form.as_p}}
            <button type="submit" class="btn btn-primary">Add</button>
            <a href="{% url 'market' market_list.id %}" class="btn btn-secondary">Go Back</a>
        </form>
    {% endif %}
</div>
{% endblock %}

website/market/templates/base.html
<!doctype html>
<html lang="en" data-bs-theme="dark">
    <head>
        <meta charset="utf-8">
        <meta name="viewport" content="width=device-width, initial-scale=1">
        <title>Market List</title>
        <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-T3c6CoIi6uLrA9TneNEoa7RxnatzjcDSCmG1MXxSR1GAsXEV/Dwwykc2MPK8M2HN" crossorigin="anonymous">
        <link href="https://cdn.jsdelivr.net/npm/remixicon@3.5.0/fonts/remixicon.css" rel="stylesheet">
    </head>
    <body>
        {% include 'navbar.html' %}

        <main>
            {% block content %}
            {% endblock %}
        </main>

        <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.3.2/dist/js/bootstrap.bundle.min.js" integrity="sha384-C6RzsynM9kWDrMNeT87bh95OGNyZPhcTNXj1NW7RuBCsyN/o0jlpcV8Qyq46cDfL" crossorigin="anonymous"></script>
    </body>
</html>

website/market/templates/generate_list.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <div class="d-flex justify-content-end">
        <a href="{% url 'market' market.id %}" class="btn btn-secondary">Go Back</a>
    </div>
    <h1 class="d-flex justify-content-center">{{market}}</h1>
    <h2 class="d-flex justify-content-center">generate shopping list</h2>

    {% if shopping_list %}
    <table class="table table-hover">
        <thead>
            <tr>
                <th scope="col" class="col-1"></th>
                <th scope="col" class="col-4">Name</th>
                <th scope="col" class="col-4 text-center">Quantity</th>
            </tr>
        </thead>
        <tbody class="table-group-divider">
            {% for ingredient in shopping_list %}
                <tr>
                    <td class="text-center">
                        <input class="form-check-input" type="checkbox">
                    </td>
                    <td>{{ingredient.name}}</td>
                    <td class="text-center">
                        {% if ingredient.gr != 0 %}
                            {{ingredient.gr}} gr
                        {% endif %}
                        {% if ingredient.un != 0%}
                            {{ingredient.un}} uni
                        {% endif %}
                    </td>
                </tr>
            {% endfor %}
        </tbody>
    </table>
    {% endif %}
</div>
{% endblock %}

website/market/templates/home.html
{% extends "base.html" %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1 class="d-flex justify-content-center"> Market Shopping List </h1>
    <span>
        Generate your shopping lists based on the recipes you define. Create your lists of recipes to keep them in order.
    </span>
    {% if user.is_authenticated %}
        <section>
            <h2>All Market Shopping List</h2>
            <div class="d-flex justify-content-end">
                <a href="{% url 'add_market' %}" class="btn btn-primary">Add</a>
            </div>
            {% if market_list %}
                <table class="table table-hover">
                    <thead>
                        <tr>
                            <th scope="col" class="col-8">Market name</th>
                            <th scope="col" class="col-2 text-center">Options</th>
                        </tr>
                    </thead>
                    <tbody class="table-group-divider">
                        {% for market in market_list %}
                            <tr>
                                <td>
                                    <a href="{% url 'market' market.id %}" class="icon-link text-decoration-none">{{market.name}}</a>
                                </td>
                                <td class="text-center">
                                    <a href="{% url 'update_market' market.id %}" class="icon-link text-decoration-none"><i class="ri-edit-box-fill"></i></a>
                                    <a href="{% url 'delete_market' market.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                                </td>
                            </tr>
                        {% endfor %}
                    </tbody>
                </table>
            {% else %}
                <p>No recipes avaible</p>
            {% endif %}
        </section>
    {% else %}
        <div class="col-md-6 offset-md-3">
            <h1>Login</h1>
            <form action="{% url 'home' %}" method="post">
                {% csrf_token %}
                <div class="mb-3">
                    <input type="text" class="form-control" name="username" placeholder="username" required>
                </div>
                <div class="mb-3">
                    <input type="password" class="form-control" name="password" placeholder="Password" required>
                </div>
                <button type="submit" class="btn btn-primary">Login</button>
            </form>
        </div>
    {% endif %}
</div>
{% endblock %}

website/market/templates/ingredients_list.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Ingredients</h1>
    <div class="d-flex justify-content-end">
        <a href="{% url 'add_ingredient' %}" class="btn btn-primary">Add</a>
    </div>
    {% if Vegetables or Meat or Dairy or Condiment or Fruits or Pasta %}
        {% if Vegetables %}
            <h2>Vegetables</h2>
            <ul class="list-group">
                {% for vegetable in Vegetables%}
                    <li class="list-group-item d-flex justify-content-between">
                        {{vegetable.name}}
                        <a href="{% url 'delete_ingredient' vegetable.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if Meat %}
            <h2>Meats</h2>
            <ul class="list-group">
                {% for meat in Meat %}
                <li class="list-group-item d-flex justify-content-between">
                        {{meat.name}}
                        <a href="{% url 'delete_ingredient' meat.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if Dairy %}
            <h2>Dairies</h2>
            <ul class="list-group">
                {% for dairy in Dairy%}
                <li class="list-group-item d-flex justify-content-between">
                        {{dairy.name}}
                        <a href="{% url 'delete_ingredient' dairy.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if Condiments %}
            <h2>Condiments</h2>
            <ul class="list-group">
                {% for condiment in Condiments%}
                <li class="list-group-item d-flex justify-content-between">
                        {{condiment.name}}
                        <a href="{% url 'delete_ingredient' condiment.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if Fruits %}
            <h2>Fruits</h2>
            <ul class="list-group">
                {% for fruit in Fruits%}
                <li class="list-group-item d-flex justify-content-between">
                        {{fruit.name}}
                        <a href="{% url 'delete_ingredient' fruit.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
        {% if Pasta %}
            <h2>Pastas</h2>
            <ul class="list-group">
                {% for pasta in Pasta%}
                <li class="list-group-item d-flex justify-content-between">
                        {{pasta.name}}
                        <a href="{% url 'delete_ingredient' pasta.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </li>
                {% endfor %}
            </ul>
        {% endif %}
    {% else %}
        <p>No ingredients avaible</p>
    {% endif %}
</div>
{% endblock %}

website/market/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-body-tertiary">
    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'home' %}">Market List</a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'recipes_list' %}">Recipes</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'ingredients_list' %}">Ingredients</a>
                    </li>
                {% endif %}
            </ul>
            <ul class="navbar-nav d-flex justify-content-end">
                {% if user.is_authenticated %}
                    <li class="nav-item">
                        {{user.username}}
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'logout' %}">Logout</a>
                    </li>
                {% else %}
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'register' %}">Register</a>
                    </li>
                    <li class="nav-item">
                        <a class="nav-link" href="{% url 'home' %}">Login</a>
                    </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>

website/market/templates/recipe.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    {% if recipe %}
        <div class="d-flex justify-content-end">
            <a href="{% url 'recipes_list' %}" class="btn btn-secondary">Go Back</a>
        </div>
        <div class="d-flex flex-column align-items-center">
            <h2>Recipe</h2>
            <h1>{{recipe}}</h1>
        </div>

        <div class="d-flex justify-content-between">
            <h3>List of Ingredients</h3>
            <a href="{% url 'add_ingredient_to_recipe' recipe.id %}" class="btn btn-primary">Add</a>
        </div>
        {% if ingredients_detail %}
            <table class="table table-hover">
                <thead>
                    <tr>
                        <th scope="col" class="col-4">Name</th>
                        <th scope="col" class="col-4">Categorie</th>
                        <th scope="col" class="col-3">Quantity</th>
                        <th scope="col" class="col-1 text-center">Option</th>
                    </tr>
                </thead>
                <tbody class="table-group-divider">
                    {% for ingredient in ingredients_detail %}
                        <tr>
                            <td>{{ingredient.ingredient}}</td>
                            <td>{{ingredient.ingredient.get_categorie_display}}</td>
                            <td>{{ingredient.value}} {{ingredient.unity}}</td>
                            <td class="text-center">
                                <a href="{% url 'delete_ingredient_from_recipe' recipe.id ingredient.ingredient.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                            </td>
                        </tr>
                    {% endfor %}
                </tbody>
            </table>
        {% else %}
            <p>No ingredients on the recipe avaible</p>
        {% endif %}
    {% endif%}
</div>
{% endblock %}

website/market/templates/recipes_list.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Recipes List</h1>

    <div class="d-flex justify-content-end">
        <a href="{% url 'add_recipe' %}" class="btn btn-primary ">Add Recipe</a>
    </div>

    {% if recipes_list %}
        <table class="table table-hover">
            <thead>
                <tr>
                    <th scope="col" class="col-8">Recipes name</th>
                    <th scope="col" class="col-2 text-center">Options</th>
                </tr>
            </thead>
            <tbody class="table-group-divider">
                {% for recipe in recipes_list %}
                <tr>
                    <td>
                        <a href="{% url 'recipe' recipe.id %}" class="icon-link text-decoration-none">{{recipe.name}}</a>
                    </td>
                    <td class="text-center">
                        <a href="{% url 'update_recipe' recipe.id %}" class="icon-link text-decoration-none"><i class="ri-edit-box-fill"></i></a>
                        <a href="{% url 'delete_recipe' recipe.id %}" class="icon-link text-decoration-none"><i class="ri-delete-bin-line"></i></a>
                    </td>
                </tr>
                {% endfor %}
            </tbody>
        </table>
    {% else %}
        <p>No recipes avaible</p>
    {% endif %}
</div>
{% endblock %}

website/market/templates/register.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Register</h1>

    <form method="post" action="">
        {% csrf_token %}

        {% if form.errors %}
            <div class="alert alert-warning alert-dismissible fade show" role="alert">
                Your registration has errors
                {% for field in form %}
                    {% if field.errors %}
                        {{ field.errors }}
                    {% endif %}
                {% endfor %}
                <button type="button" class="btn-close" data-bs-dismiss="alert" aria-label="Close"></button>
            </div>
        {% endif %}
        {{form.username}}
        {{form.first_name}}
        {{form.last_name}}
        {{form.email}}
        {{form.password1}}
        {{form.password2}}
        <button type="submit" class="btn btn-primary">Register</button>
    </form>
</div>
{% endblock %}

website/market/templates/update_market.html
{% extends 'base.html' %}

{% block content %}
<div class="col-md-6 offset-md-3">
    <h1>Update Market Name</h1>

    <form action="" method="post">
        {% csrf_token %}
        {{form.as_p}}
        <button type="submit" class="btn btn-primary">Update</button>
        <a href="{% url 'home' %}" class="btn btn-secondary">Go Back</a>
    </form>
</div>
{% endblock%}